# code formatter settings:
[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env
  | venv
)/
'''

# Set root for pytest: https://stackoverflow.com/a/50610630
[tool.pytest.ini_options]
pythonpath = [
  "."
]
