name: unitary

on: ["push"]

jobs:
  unitary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Compiler Installations
        uses: actions/cache@v3
        with:
          path: ~/.vvm
          key: compiler-cache

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6

      - name: Install Requirements
        run: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

      - name: Run Tests
        run: pytest -n 16
        env:
          RPC_ETHEREUM: ${{ secrets.RPC_ETHEREUM }}
